// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://outyvqiykhrtbsiobmcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91dHl2cWl5a2hydGJzaW9ibWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTExMzgsImV4cCI6MjA2ODY2NzEzOH0.ietg0hvE-BmqhG8HCSjvt7IeryTbmfzv5oVxbijLVYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});